feat: Initial commit of Project Structure, Components & Storybook
pesto-students/n7-dreamstock-frontend-iota-1 pull request #2
Opened 2021-09-16 11:09 UTC by AbhinavDegala

2021-09-16 16:06 UTC, ShashankSuresh requested changes

2021-09-16 16:06 UTC, ShashankSuresh commented on src/index.css
> +/* body {
Remove this

2021-09-16 16:06 UTC, ShashankSuresh commented on src/components/Span.js
> +  ${compose(space, position, layout, typography)}
Please add font weight here

2021-09-16 16:06 UTC, ShashankSuresh commented on src/stories/Icons.stories.jsx
> +export const AppLogo = () => <img alt="logo" src={Logo} height="40"></img>;
Create a component called Logo.js and pass src as its prop

2021-09-17 01:10 UTC, AbhinavDegala commented
Made the specified changes

2021-09-17 01:10 UTC, closed without merging